import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "./components/Navbar";
import Providers from "./Providers";


export const metadata: Metadata = {
  title: "Quiniela 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Nav/>
      <main className="flex min-h-screen flex-col items-center justify-between p-24 bg-gradient-to-b from-sky to-white overflow-hidden">
        <Providers>
        { children}
        </Providers>
      </main></body>
    </html>
  );
}
